# Generated by Django 3.0 on 2019-12-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191217_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='mileage',
            field=models.IntegerField(default=100),
        ),
    ]
