# Generated by Django 3.0 on 2019-12-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_motorcycle_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='maint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.IntegerField()),
                ('maintenance', models.CharField(choices=[('Oil', 3000), ('Chain', 500), ('Tires', 7000)], default='Oil', max_length=50)),
            ],
        ),
    ]
